### ISSUE TITLE
Crashea pestaña de preinscripción con ciertas materias

### ISSUE THREAD

**Issue by soriac** [pablomatiasgomez/siga-helper-chrome#1]
Primero que nada quería agradecer por la excelente extensión para chrome, super útil, verdaderamente agrega mucha utilidad a un sistema que le hace mucha falta.

Hoy me estaba preinscribiendo a algunas materias y me dí cuenta que en cuanto agrego la materia "Técnicas de Gráficos por Computadoras", que es a la noche, la pestaña deja de responder y eventualmente crashea.

A un amigo le pasa algo similar, pero dice que es porque se superponen dos horarios en el día miércoles (en el bloque horario 2).

Me fijé si la consola tiraba algo antes de crashear, pero nada. Adjunto screenshot de mi horario y el horario de mi amigo, quizas sirva para debuggear.

![chrome_2018-02-19_16-03-31](https://user-images.githubusercontent.com/12989318/36393615-118cf43e-158f-11e8-931a-13ebb24270ee.png)

![image](https://user-images.githubusercontent.com/12989318/36393672-4dd0637c-158f-11e8-8b11-f7e409a372d8.png)

**Comment by pablomatiasgomez** [comment]
Mil gracias por el aporte! Muy buen detallado, y los screenshots fueron clave. Había un loop infinito para crear el color que se muestra en la tabla por materia :) Ya tengo el fix y en minutos lo publico al store!
Gracias!
