### ISSUE TITLE
Busqueda de profesores y cursos rota

### ISSUE THREAD

**Issue by Matiasga98** [pablomatiasgomez/siga-helper-chrome#13]
Hola! recién estábamos con unos amigos y queríamos buscar las opiniones de profesores y cursos pero no aparece nada cuando buscas. Esto antes andaba perfecto. gracias de antemano y por haber hecho esta extensión, es re útil!

**Comment by pablomatiasgomez** [comment]
Hola @Matiasga98 gracias por avisar! Se me cayo el server y no tengo ninguna alarma por ahora. Ya está andando nuevamente :) 

Saludos!
