### ISSUE TITLE
Soporte para planes anteriores

### ISSUE THREAD

**Issue by davidosvaldoperez** [pablomatiasgomez/siga-helper-chrome#4]
En la sección de "Listado", aparece un seguidor de carrea muy piola para ver que materias faltan y cuales son los requisitos.

El problema que se presenta es que, para materias aprobadas en planes anteriores, las materias figuran como "PENDIENTE". Esto se debe a que los codigos de materia no coinciden.

¿Quizas hay manera de consultar los planes anteriores para hacer una equivalencia?

![image](https://user-images.githubusercontent.com/26714968/53662259-3d453f80-3c41-11e9-93d4-88258ee34317.png)

![image](https://user-images.githubusercontent.com/26714968/53662423-a2993080-3c41-11e9-9b63-b70dfeb641c8.png)

**Comment by jlavera** [comment]
Buenas!
El listado de materias es en realidad un proyecto aparte desarrollado por mi y que junto con pablo, lo integramos en el siga.
La realidad es que soportar otros planes (ya sea anteriores u otras carreras) es algo que tenia ganas de implementar desde hace rato, pero lleva tiempo y por el momento estaba priorizando otros features (aunque tampoco le estoy dedicando todo el tiempo que deberia....).
La idea es terminar de agregar las materias optativas que estan a mitad de camino, luego login (ahora se guarda la informacion en las cookies) y despues nuevos planes.

Te puedo avisar por aca cuando avance :)
Saludos!

**Comment by pablomatiasgomez** [comment]
Won't fix.

**Comment by pablomatiasgomez** [comment]
@davidosvaldoperez Hay una nueva sección en el siga helper "Seguimiento de Plan" donde podes ver el plan con las materias que tenes aprobadas. Se tienen en cuenta planes anteriores. Avisame si encontras algo! Slds
