### ISSUE TITLE
Pagina caida

### ISSUE THREAD

**Issue by ncoen97** [pablomatiasgomez/siga-helper-chrome#5]
Buenas, por las dudas informo que la pagina esta caída y no muestra el listado de materias desde el siga.
Saludos.

**Comment by pablomatiasgomez** [comment]
cc @jlavera

**Comment by jlavera** [comment]
Se, ya se, lo tengo que volver a levantar... Fue un semestre bastante ocupado :(

**Comment by pablomatiasgomez** [comment]
Won't fix.
